import {postCardProps} from "@/src/components/ui/postCard";

export const PostData:postCardProps[] = [
    {
        id: '1',
        name:'testing',
        location:'Noida, Uttar Pradesh',
        imageUrl:'https://contentstatic.techgig.com/photo/87178282/techgig-daily-tech-news-digest-21-october.jpg?1288695',
        postDate:'Jul 1, 2025',
        postContent:'Technology | ',
        views:'3 Views ',
        discription:'vsveee',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Technology',
    },
    {
        id: '2',
        name:'zoya',
        location:'Jaipur, Rajasthan',
        imageUrl:'https://plus.unsplash.com/premium_photo-1675198764473-30434364c8b6?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bmF0dXJlJTIwYmFja2dyb3VuZHxlbnwwfHwwfHx8MA%3D%3D',
        postDate:'Jul 1, 2025',
        postContent:'Nature | ',
        views:'30 Views ',
        discription:'nothing much',
        fullLocation:' Mansarovar, Jaipur, Rajasthan, 302020 ',
    },
    {
        id: '3',
        name:'Anonymouse',
        location:'Noida, Uttar Pradesh',
        imageUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1ZtIYG3EE_cSzihfHWp2I92684TeHmsS5mg&s',
        postDate:'Jul 1, 2025',
        postContent:'Architecture | ',
        views:'30k Views ',
        discription:'vsveee',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Business',
    },
    {
        id: '4',
        name:'tupen',
        location:'Bishnupur, West Bengal',
        imageUrl:'https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnVzaW5lc3MlMjBuZXdzfGVufDB8fDB8fHww',
        postDate:'Jul 1, 2025',
        postContent:'Architecture | ',
        views:'3 Views ',
        discription:'vsveee',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Business',
    },
    {
        id: '5',
        name:'tupen',
        location:'Bishnupur, West Bengal',
        imageUrl:'https://tvcentertainment.tv/wp-content/uploads/2024/07/1722294956_maxresdefault.jpg',
        postDate:'Jul 1, 2025',
        postContent:'Architecture | ',
        views:'3 Views ',
        discription:'vsveee',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Entertainment',
    },
    {
        id: '6',
        name:'Ritu',
        location:' West Bengal',
        imageUrl:'https://www.jansatta.com/wp-content/uploads/2025/01/Add-a-heading-2.jpg?w=440',
        postDate:'Jul 1, 2025',
        postContent:'EndLessPoint | ',
        views:'31 Views ',
        discription:'Just for fun',
        fullLocation:'Meerut Division, Uk 20209 ',
        category: 'Entertainment',
    },
    {
        id: '7',
        name:'Rohan Jha',
        location:'Goa',
        imageUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVa-DGLzhUcxOBD1fsvYDGJIBa4LjumFxvWg&s',
        postDate:'Jul 1, 2025',
        postContent:'Architecture | ',
        views:'300k Views ',
        discription:'Nothing much',
        fullLocation:'Goa,  Meerut Division, UH 30394 ',
        category: 'Entertainment',
    },
    {
        id: '8',
        name:'Aman Verma',
        location:'Baliya UP 20303',
        imageUrl:'https://c.ndtvimg.com/2025-06/6fc0a7k4_jasprit-bumrah-afp_625x300_22_June_25.jpg?im=FeatureCrop,algorithm=dnn,width=521,height=292',
        postDate:'Jul 1, 2025',
        postContent:'Architecture | ',
        views:'20k Views ',
        discription:'Test Cricket',
        fullLocation:'Baliya UP 20303, Jaunpur',
        category: 'Sports',
    },
    {
        id: '9',
        name:'VijayMal Yadav',
        location:'Jaunpur Uttar Pradesh',
        imageUrl:'https://mmo.aiircdn.com/265/685a37fcb5cf1.jpg',
        postDate:'Jul 1, 2025',
        postContent:'Architecture | ',
        views:'10k Views ',
        discription:'Test Cricket',
        fullLocation:'Jaunpur, Uttar Pradesh 20003 ',
        category: 'Sports',
    },
    {
        id: '10',
        name:'Shivam Singh',
        location:'Ayodhya Uttar Pradesh 1229',
        imageUrl:'https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2024/12/top-ten-sport-news-eng-9-1733115105.jpg',
        postDate:'Jul 1, 2025',
        postContent:'Architecture | ',
        views:'5k Views ',
        discription:'Test Cricket',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Sports',
    },
    {
        id: '11',
        name:'Nihar',
        location:'Noida, Uttar Pradesh',
        imageUrl:'https://images.indianexpress.com/2024/01/tech-news-listicle-featured.jpg',
        postDate:'Jul 1, 2025',
        postContent:'Technology | ',
        views:'3 Views ',
        discription:'Tech',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Technology',
    },
    {
        id: '12',
        name:'Prv Verma',
        location:'Noida, Uttar Pradesh',
        imageUrl:'https://www.simplilearn.com/ice9/free_resources_article_thumb/Technology_Trends.jpg',
        postDate:'Jul 1, 2025',
        postContent:'Technology | ',
        views:'1k Views ',
        discription:'Tech Hub',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Technology',
    },
    {
        id: '13',
        name:'testing',
        location:'Noida, Uttar Pradesh',
        imageUrl:'https://media.istockphoto.com/id/1032637132/photo/a-cup-of-coffee-glasses-and-newspaper-titled-health-medical.jpg?s=612x612&w=0&k=20&c=W52Q_4CXrdJs24wI_5qt4t72Hcs1AzpzkoSzntByUoY=',
        postDate:'Jul 1, 2025',
        postContent:'Technology | ',
        views:'3 Views ',
        discription:'vsveee',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Health',
    },
    {
        id: '14',
        name:'testing',
        location:'Noida, Uttar Pradesh',
        imageUrl:'https://media.post.rvohealth.io/wp-content/uploads/sites/3/2025/06/measles-vaccination-vial-732x549-thumbnail.jpg',
        postDate:'Jul 1, 2025',
        postContent:'Technology | ',
        views:'3 Views ',
        discription:'yummmyy',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Health',
    },
    {
        id: '15',
        name:'testing',
        location:'Noida, Uttar Pradesh',
        imageUrl:'https://media.post.rvohealth.io/wp-content/uploads/sites/3/2025/06/calendar-circled-date-732x549-thumbnail.jpg',
        postDate:'Jul 1, 2025',
        postContent:'Technology | ',
        views:'3 Views ',
        discription:'vsveee',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Health',
    },
    {
        id: '16',
        name:'testing',
        location:'Noida, Uttar Pradesh',
        imageUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmVBuCuiacWc0WXhP24f1daNy8HuYiEmhGkw&s',
        postDate:'Jul 1, 2025',
        postContent:'Technology | ',
        views:'3 Views ',
        discription:'vsveee',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Health',
    },
    {
        id: '17',
        name:'Anonymouse',
        location:'Noida, Uttar Pradesh',
        imageUrl:'https://feeds.abplive.com/onecms/images/uploaded-images/2025/06/24/c3ed74ab00d38b3f4690a888570e97fd1750762110714809_original.jpg?impolicy=abp_cdn&imwidth=381',
        postDate:'Jul 1, 2025',
        postContent:'Architecture | ',
        views:'30k Views ',
        discription:'vsveee',
        fullLocation:'Noida Sector 3 , Noida, Meerut Division, UP ',
        category: 'Business',
    },
]
